Eureka-projectFactoriaF5/buzon-inteligente-BE

- .gitignore
- src/main/java/com/f5/buzon_inteligente_BE/model/User.java
Creamos el class User, con sus constructores para tabla users.
[BUZ-48](https://grigorivladimiro.atlassian.net/browse/BUZ-48)
[BUZ-48]: https://grigorivladimiro.atlassian.net/browse/BUZ-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Buz 48 Crear Modelo User

- src/main/java/com/f5/buzon_inteligente_BE/config/CorsConfig.java
- src/main/java/com/f5/buzon_inteligente_BE/model/User.java
[Jira](https://grigorivladimiro.atlassian.net/browse/BUZ-47)
Implementar una clase de configuración (CorsConfig) en el backend con Spring Boot para habilitar y controlar el intercambio de recursos entre el frontend y el backend (Cross-Origin Resource Sharing - CORS).
La configuración debe permitir solicitudes desde los orígenes autorizados, incluyendo los métodos y encabezados necesarios, para facilitar el acceso desde el cliente (por ejemplo, React o aplicaciones móviles).
Criterios de aceptación:
Se crea una clase CorsConfig anotada con @Configuration.
Se implementa un bean de tipo CorsConfigurationSource o se extiende WebMvcConfigurer.
Se permite el origen del frontend (ej. http://localhost:3000) o variables de entorno para despliegue.
Se habilitan los métodos HTTP necesarios: GET, …
> feat: Implement COR config

- src/test/java/com/f5/buzon_inteligente_BE/security/JwtUtilsTest.java
Changes Included
-  Initialized JwtUtilsTest class with setup and common test data.
- Added test for JWT token generation.
- Added test for successful token validation.
- Added test for extracting username and claims from JWT.
-  Added test for detecting expired tokens.
- Added test for extracting JWT from Authorization header.
- Added test for Authorization header missing 'Bearer' prefix.
- Added test for malformed JWT tokens.
-  Added test for unsupported JWT tokens.
- Added test for empty JWT tokens.
- Added test for null Authorization header.
[Test de generación y validación de JWT.](https://mabelrincon.atlassian.net/browse/TEST-3)
> TEST-3 Test de generación y validación de JWT.

- src/main/java/com/f5/buzon_inteligente_BE/security/CustomUserDetails.java
- src/main/java/com/f5/buzon_inteligente_BE/security/CustomUserDetailsService.java
feat: add custom user details and custom user details service
[crear user details service](https://grigorivladimiro.atlassian.net/browse/BUZ-138)
> crear user details service

- src/test/java/com/f5/buzon_inteligente_BE/security/CustomUserDetailsTest.java
✅ Implemented unit tests for CustomUserDetails with complete branch and line coverage.
[TEST-5-test-custom-user-details](https://mabelrincon.atlassian.net/browse/TEST-5?atlOrigin=eyJpIjoiZDYwYmQ0NjMyNzY4NGYwYmE5YmQyNDhlNTdiNmMxYjMiLCJwIjoiaiJ9)
> TEST-5-test-custom-user-details

- src/test/java/com/f5/buzon_inteligente_BE/config/CorsConfigTest.java
- src/test/resources/application-test.properties
This Pull Request includes the complete test environment setup for the application and the implementation of a comprehensive CORS configuration test suite.
- **Created `application-test.properties`** with:
- In-memory H2 database configuration for testing.
- Default JWT properties (`JWT_SECRET` and `JWT_EXPIRATION`) to prevent ApplicationContext loading failures during tests.
- **Implemented `CorsConfigTest.java`** which includes:
- ✔️ Test to verify that CORS preflight requests from the allowed frontend origin are accepted.
- ✔️ Test to verify that CORS requests from disallowed origins are properly blocked.
- ✔️ Test to ensure multiple HTTP methods are allowed in CORS configuration.
- ✅ Usage of `@TestConfiguration` to inject a mocked `JwtUtils` dependency, avoiding deprecated …
> TEST-15 Test: CORS Configuration + Test Environment Setup

- src/main/java/com/f5/buzon_inteligente_BE/mailbox/Mailbox.java
se creo la entidad mailbox con sus respectivas relaciones, constructors, getters y setters.
> Buz 160 crear entidad mailbox

- src/main/java/com/f5/buzon_inteligente_BE/accesscode/AccessCode.java
Diseñar entidad para código de acceso
Crear una tabla en la base de datos que almacene los códigos alfanuméricos generados y su relación con los paquetes.
Criterios de aceptación:.
- Se establece una relación uno-a-muchos entre códigos y paquetes (parceles).
- La unicidad del código está garantizada.
> feat: Add AccessCode entity with relationships and fields

- src/main/java/com/f5/buzon_inteligente_BE/accesscode/AccessCode.java
- src/main/java/com/f5/buzon_inteligente_BE/locker/Locker.java
- src/main/java/com/f5/buzon_inteligente_BE/parcel/Parcel.java
Fue necesario renombrar la clase/entidad a Parcel ya que "package" es una palaba reservada de Java.
Implementación de la clase:
Persistencia con JPA: 
- Se define la entidad Parcel con sus respectivas anotaciones para el mapeo en la base de datos.
Relaciones:
- ManyToOne con AccessCode para asociar un código de acceso al paquete.
- OneToOne con Mailbox para registrar el buzón de entrega.
Gestión de tiempos:
- deliveryDate: Fecha de entrega establecida como el momento de la creación del objeto.
- alarmDate: Configurable para generar alertas previas a la expiración del plazo.
- deadlineDate: Determinado en función del tiempo límite del casillero
En Locker se modificó el tipo de dato que es timeLimit. Si hay posibilidad de manejar tiempos extensos, Long es más seguro para evitar …
> Buz 165 crear entidad packages

- src/main/java/com/f5/buzon_inteligente_BE/parcel/Parcel.java
Completando el UML me di cuenta que no estaba el método para recuperar el Id.
> feat: getParcelId added

- src/test/java/com/f5/buzon_inteligente_BE/roles/RoleRepositoryIntegrationTest.java
- src/test/java/com/f5/buzon_inteligente_BE/roles/RoleServiceTest.java
- src/test/java/com/f5/buzon_inteligente_BE/roles/RoleTest.java
Este Pull Request añade una suite completa de pruebas de integración para el repositorio `RoleRepository`, abarcando tanto casos estándar como casos límite (*edge cases*). Estas pruebas garantizan el correcto funcionamiento y la robustez de la capa de persistencia de roles en la aplicación.
---
- `testShouldSaveAndFindById`: Verifica que un rol se guarda correctamente y se puede recuperar por su ID.
- `testShouldFindByRoleName`: Valida la recuperación exitosa de un rol por su nombre (`roleName`).
- `testShouldRoleNameNotFound`: Asegura que se retorna vacío si el nombre de rol no existe.
- `testShouldEmptyRoleName`: Evalúa el comportamiento ante una cadena vacía.
- `testShouldWhitespaceRoleName`: Evalúa el comportamiento ante espacios en blanco.
- `testShouldNullRoleName`: Evalúa el …
> TEST-51 Tests de integración para RoleRepository 

- src/test/java/com/f5/buzon_inteligente_BE/security/CustomUserDetailsServiceTest.java
Se ha añadido la clase CustomUserDetailsServiceTest para testear el servicio de autenticación CustomUserDetailsService.
✅ Cambios realizados
Se han añadido dos tests unitarios utilizando JUnit 5 y Mockito:
- testLoadUserByEmail: verifica que se carga correctamente un usuario existente por email.
- testLoadUserByEmailNotExist: verifica que se lanza una excepción UsernameNotFoundException cuando el email no existe en la base de datos.
[TEST-12 Testing Pull Request #8 - Test CustomUserDetailsService](https://mabelrincon.atlassian.net/browse/TEST-12)
> TEST-12 Test customUserDetailsService with exception

- src/test/java/com/f5/buzon_inteligente_BE/auth/login/LoginControllerTest.java
- src/test/java/com/f5/buzon_inteligente_BE/auth/login/LoginRequestDtoTest.java
- src/test/java/com/f5/buzon_inteligente_BE/auth/login/LoginResponseDtoTest.java
- src/test/java/com/f5/buzon_inteligente_BE/auth/login/LoginServiceTest.java
Esta PR añade una batería de pruebas unitarias para cubrir el flujo de autenticación de usuario, abarcando los DTOs, el `LoginService` y el `LoginController`.
- **LoginRequestDtoTest**: Verifica el correcto almacenamiento y recuperación de los campos `email` y `password`.
- **LoginResponseDtoTest**: Asegura el correcto funcionamiento de los getters `token`, `role` y `message`.
- Prueba de autenticación exitosa, incluyendo:
- Codificación Base64 de la contraseña.
- Simulación de `AuthenticationManager` y `JwtUtils`.
- Casos negativos:
- Contraseña vacía.
- Contraseña nula.
- Contraseña mal codificada (no Base64).
- `testLogin`: Flujo completo de login exitoso con verificación de contenido del JSON (`token`, `role`, `message`).
- `testLoginFail`: Simulación de credenciales incorrectas …
> TEST-19 testing pull request 15 auth login

- src/test/java/com/f5/buzon_inteligente_BE/auth/register/RegisterRequestTest.java
Se añade la clase de test `RegisterRequestTest` para verificar el correcto funcionamiento de los métodos `get` y `set` de la clase `RegisterRequest`, utilizada durante el proceso de registro de usuario.
- Añadido test unitario para cada uno de los métodos `getter`:
- `getUserDni`
- `getUserName`
- `getUserSurname`
- `getUserEmail`
- `getUserPassword`
- Añadido test unitario para cada uno de los métodos `setter`:
- `setUserDni`
- `setUserName`
- `setUserSurname`
- `setUserEmail`
- `setUserPassword`
- Se incluyen pruebas tanto para instancias con valores como para instancias vacías (`RegisterRequest()`).
> Test 50 testing pull request 18 subtask test register request

- src/main/java/com/f5/buzon_inteligente_BE/auth/login/LoginService.java
- src/main/java/com/f5/buzon_inteligente_BE/security/CustomUserDetails.java
- src/main/java/com/f5/buzon_inteligente_BE/security/CustomUserDetailsService.java
- src/main/java/com/f5/buzon_inteligente_BE/security/JwtUtils.java
Implementé el userId para que Alejandro pueda hacer sus cositas :)
> fix: implemented userId in jwt security

- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxRepository.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxService.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxSize.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxSizeRepository.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxStatusRepository.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/exceptions/MailboxNotFoundException.java
se implementa la capa service de la entidad mailbox con sus respectivos repositorios y excepciones. también se añade el atributo capacity en mailbox size para implementar la lógica de forma mas apropiada
> Buz 67 mailbox service implementar lógica para asignar buzones disponibles en base al tamaño

- src/test/java/com/f5/buzon_inteligente_BE/profile/ProfileServiceTest.java
Se agrega la clase `ProfileServiceTest` utilizando **JUnit 5** y **Mockito** para cubrir exhaustivamente la lógica del servicio `ProfileService`. Esta clase asegura el correcto funcionamiento de las operaciones CRUD, búsqueda y regeneración de credenciales para los perfiles de usuario.
---
Los siguientes métodos han sido testeados exitosamente:
- `getAllProfiles()`
- `getProfileById(Long id)`
- `getProfileByUserId(Long userId)`
- `getProfileByPermanentCredential(String credential)`
- `createProfile(Long userId)`
- `updateProfile(Long id, String credential)`
- `deleteProfile(Long id)`
- `regeneratePermanentCredential(Long id)`
---
- Retornar todos los perfiles existentes.
- Obtener un perfil por ID, por `userId` y por `permanentCredential`.
- Crear un perfil nuevo si no existe y el usuario …
> TEST-56  Test Profile Service

- src/main/java/com/f5/buzon_inteligente_BE/config/SecurityConfig.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxController.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxRepository.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxResponseDto.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxService.java
- src/main/java/com/f5/buzon_inteligente_BE/mailbox/MailboxStatusRepository.java
se agrega el mailbox controller con endpoint GET /api/mailboxes/available?mailboxSizeId=1
y el mailbox response dto
> Buz 92 mailbox controller

- src/test/java/com/f5/buzon_inteligente_BE/profile/dto/UserProfileResponseDTOTest.java
Este PR agrega la clase de test `UserProfileResponseDTOTest` para cubrir completamente el DTO `UserProfileResponseDTO` .
- **Should create object with null fields when using empty constructor**  
Verifica que los campos sean `null` al instanciar sin argumentos.
- **Should correctly set all fields using constructor with arguments**  
Comprueba que se asignen correctamente los valores.
- **Should map data correctly from User and Profile in fromEntities**  
Asegura el mapeo correcto de datos desde las entidades `User` y `Profile`.
- **Should allow updating fields using setters**  
Valida que los campos puedan actualizarse correctamente.
- **Should throw NullPointerException when user is null in fromEntities**  
Verifica el comportamiento cuando `User` es `null`.
- **Should throw …
> TEST-58  Test de UserProfileResponseDTO

- src/test/java/com/f5/buzon_inteligente_BE/parcel/ParcelTest.java
Esta PR añade una suite  de pruebas unitarias para la clase `Parcel` , cubriendo tanto casos estándar como escenarios límite.
- Verificación de getters:
- `getAccessCode()`
- `getMailbox()`
- `getDeliveryDate()`
- `getAlarmDate()`
- `getDeadlineDate()`
- Prueba de lógica personalizada:
- `setAlarmDate(Long alarmHours)`
- `setDeadlineDate(Locker locker)`
- Manejo de edge cases:
- `setAlarmDate(0L)` → igual a `deadlineDate`
- `setAlarmDate(-2L)` → mayor que `deadlineDate`
- `setDeadlineDate()` con `timeLimit = 0` → igual a `deliveryDate`
- `setDeadlineDate()` con `timeLimit < 0` → menor que `deliveryDate`
- Comparaciones temporales ajustadas con `.withNano(0)` para evitar errores por nanosegundos en los tests.
> Test 64 -Tests para `Parcel`

- src/main/java/com/f5/buzon_inteligente_BE/parcel/ParcelRepository.java
- src/main/java/com/f5/buzon_inteligente_BE/parcel/ParcelService.java
- src/main/java/com/f5/buzon_inteligente_BE/parcel/dto/ParcelResponseDTO.java
--
- **Nuevo `ParcelRepository`**  
- Añadido el método `findTopByAccessCodeOrderByDeliveryDateDesc` para obtener el último paquete entregado asociado a un `AccessCode`.
- **Nuevo `ParcelService`**  
- Implementado el método `createParcelAndUpdateAccessCodeStatus` que:
- Verifica si el último paquete asociado a un código de acceso ha vencido.
- Si venció, actualiza el estado del `AccessCode` a **"No recogido"** y guarda el cambio.
- Si no ha vencido, permite la creación de un nuevo paquete.
- Crea y guarda un nuevo `Parcel` con fecha de entrega actual y fecha límite calculada.
- **Nuevo `ParcelResponseDTO`**  
- Clase DTO para estructurar las respuestas de la entidad `Parcel`.
- Proporciona los siguientes campos:
- `parcelId`
- `accessCode`
- `mailboxId`
- `mailboxNumber`
- `deliveryDate` …
> Buz 61 -Crear ParcelService y ParcelResponseDTO para gestionar creación de paquetes y actualización de estado de códigos de acceso
